### ISSUE TITLE
Debian packages are uninstallable

### ISSUE THREAD

**Issue by aptituz** [grafana/metrictank#1117]
Hi there,

I tried to install Metrictank in a test setup with Ubuntu Xenial, using the instructions in https://github.com/grafana/metrictank/blob/master/docs/installation-deb.md and failed, because the packaging is incompatible with the expectations of dpkg/apt:

> dpkg: error processing archive /var/cache/apt/archives/metrictank_v0.10.0-2-g1998ca2_amd64.deb (--install):
>  parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'metrictank':
>  error in 'Version' field string 'v0.10.0-2-g1998ca2': version number does not start with digit
> dpkg: error processing archive --force-help (--install):
>  cannot access archive: No such file or directory
> Errors were encountered while processing:
>  /var/cache/apt/archives/metrictank_v0.10.0-2-g1998ca2_amd64.deb

The message is already indicating what's wrong: the version field in the package start with the letter v instead of a digit, which is required per Debian policy spec: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version

**Comment by Dieterbe** [comment]
Hi,
this was fixed a while ago. packages now look like metrictank_0.10.0-0-g1998ca2_amd64.deb, metrictank_0.11.0_amd64.deb, etc
I think in #1177

**Comment by aptituz** [comment]
Hi @Dieterbe,

unfortunately I cannot confirm that the issue is fixed.

> dpkg: error processing archive /var/cache/apt/archives/metrictank_v0.10.0-2-g1998ca2_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'metrictank':

Note: the issue is not about the *filename* of the package (dpkg doesn't care about that!) but about the Version-field in the control file.

You can check that value by looking at the output of `dpkg-deb -I` on the resulting file and currently it's like this:

```
# dpkg-deb -I /var/cache/apt/archives/metrictank_v0.10.0-2-g1998ca2_amd64.deb|grep Version
 Version: v0.10.0-2-g1998ca2
```
So I think the issue should be re-opened.

**Comment by aptituz** [comment]
Nevermind, I just figured that the testing packages are okay. So just the releases still have the bug.

**Comment by Dieterbe** [comment]
We'll check the releases
